heroes = { 
    'Hero_Andromeda': 102,
    'Hero_Engineer': 122,
    'Hero_Javaras': 37,
    'Hero_Krixi': 20,
    'Hero_Hantumon': 14,
    'Hero_Scout': 44,
    'Hero_Hiro': 15,
    'Hero_Valkyrie': 103,
    'Hero_Yogi': 30,
    'Hero_Zephyr': 31,
    'Hero_Arachna': 92,
    'Hero_Hunter': 16,
    'Hero_Chronos': 4,
    'Hero_CorruptedDisciple': 114,
    'Hero_Dampeer': 167,
    'Hero_Fade': 126,
    'Hero_FlintBeastwood': 163,
    'Hero_ForsakenArcher': 121,
    'Hero_SandWraith': 116,
    'Hero_Ebulus': 8,
    'Hero_Soulstealer': 24,
    'Hero_Vanya': 26,
    'Hero_Scar': 42,
    'Hero_Bombardier': 164,
    'Hero_DwarfMagi': 7,
    'Hero_Bubbles': 125,
    'Hero_Frosty': 12,
    'Hero_Fairy': 10,
    'Hero_Hydromancer': 166,
    'Hero_Ophelia': 36,
    'Hero_PollywogPriest':'PollywogPriest',
    'Hero_Pyromancer':'Pyromancer',
    'Hero_Tempest':'Tempest',
    'Hero_Chipper':'Chipper',
    'Hero_Kunas':'Thunderbringer',
    'Hero_Vindicator':'Vindicator',
    'Hero_WitchSlayer':'WitchSlayer',
    'Hero_Defiler':'Defiler',
    'Hero_Shaman':'DementedShaman',
    'Hero_DoctorRepulsor':'DoctorRepulsor',
    'Hero_Hellbringer':'Hellbringer',
    'Hero_DiseasedRider':'PlagueRider',
    'Hero_PuppetMaster':'PuppetMaster',
    'Hero_HellDemon':'SoulReaper',
    'Hero_Succubis':'Succubus',
    'Hero_Xalynx':'Torturer',
    'Hero_Voodoo':'VoodooJester',
    'Hero_BabaYaga':'WretchedHag',
    'Hero_Armadon':'Armadon',
    'Hero_Behemoth':'Behemoth',
    'Hero_Hammerstorm':'Hammerstorm',
    'Hero_Jereziah':'Jereziah',
    'Hero_Treant':'KeeperOfTheForest',
    'Hero_Legionnaire':'Legionnaire',
    'Hero_Panda':'Panda',
    'Hero_Rocky':'Pebbles',
    'Hero_Predator':'Predator',
    'Hero_Rampage':'Rampage',
    'Hero_Gladiator':'Gladiator',
    'Hero_Tundra':'Tundra',
    'Hero_Accursed':'Accursed',
    'Hero_Bephelgor':'Balphagore',
    'Hero_Deadwood':'Deadwood',
    'Hero_Devourer':'Devourer',
    'Hero_Electrician':'Electrician',
    'Hero_Gauntlet':'Gauntlet',
    'Hero_Kraken':'Kraken',
    'Hero_Magmar':'Magmus',
    'Hero_Maliken':'Maliken',
    'Hero_Moraxus':'Moraxus',
    'Hero_Pestilence':'Pestilence',
    'Hero_Mumra':'Pharaoh',
    'Hero_WolfMan':'WarBeast',
    'Hero_Parasite': 194,
    'Hero_MonkeyKing': 197,
    'Hero_Empath': 168}

    #'Hero_Shaman': 43, 'Hero_Krixi': 20, 'Hero_Parasite': 194, 'Hero_MonkeyKing': 197, 'Hero_Treant': 25, 'Hero_Empath': 168, 'Hero_DiseasedRider': 108, 'Hero_Bubbles':125, 'Hero_Vanya': 26, 'Hero_Engineer': 122 
def hero(name):
    return heroes[name]
