heroes = { 
    'Hero_Andromeda': 102,
    'Hero_Engineer': 122,
    'Hero_Javaras': 37,
    'Hero_Krixi': 20,
    'Hero_Hantumon': 14,
    'Hero_Scout': 44,
    'Hero_Hiro': 15,
    'Hero_Valkyrie': 103,
    'Hero_Yogi': 30,
    'Hero_Zephyr': 31,
    'Hero_Arachna': 92,
    'Hero_Hunter': 16,
    'Hero_Chronos': 4,
    'Hero_CorruptedDisciple': 114,
    'Hero_Dampeer': 167,
    'Hero_Fade': 126,
    'Hero_FlintBeastwood': 163,
    'Hero_ForsakenArcher': 121,
    'Hero_SandWraith': 116,
    'Hero_Ebulus': 8,
    'Hero_Soulstealer': 24,
    'Hero_Vanya': 26,
    'Hero_Scar': 42,
    'Hero_Bombardier': 164,
    'Hero_DwarfMagi': 7,
    'Hero_Bubbles': 125,
    'Hero_Frosty': 12,
    'Hero_Fairy': 10,
    'Hero_Hydromancer': 166,
    'Hero_Ophelia': 36,
    'Hero_PollywogPriest': 21,
    'Hero_Pyromancer': 94,
    'Hero_Tempest': 35,
    'Hero_Chipper': 124,
    'Hero_Kunas': 18,
    'Hero_Vindicator': 115,
    'Hero_WitchSlayer': 120,
    'Hero_Defiler': 5,
    'Hero_Shaman': 43,
    'Hero_DoctorRepulsor': 162,
    'Hero_Hellbringer': 93,
    'Hero_DiseasedRider': 108,
    'Hero_PuppetMaster': 91,
    'Hero_HellDemon': 109,
    'Hero_Succubis': 105,
    'Hero_Xalynx': 90,
    'Hero_Voodoo': 27,
    'Hero_BabaYaga': 104,
    'Hero_Armadon': 2,
    'Hero_Behemoth': 3,
    'Hero_Hammerstorm': 13,
    'Hero_Jereziah': 89,
    'Hero_Treant': 25,
    'Hero_Legionnaire': 38,
    'Hero_Panda': 110,
    'Hero_Rocky': 22,
    'Hero_Predator': 39,
    'Hero_Rampage': 117,
    'Hero_Gladiator': 161,
    'Hero_Tundra': 160,
    'Hero_Accursed':'Accursed',
    'Hero_Bephelgor':'Balphagore',
    'Hero_Deadwood':'Deadwood',
    'Hero_Devourer': 6,
    'Hero_Electrician':'Electrician',
    'Hero_Gauntlet': 128,
    'Hero_Kraken':'Kraken',
    'Hero_Magmar': 106,
    'Hero_Maliken':'Maliken',
    'Hero_Moraxus':'Moraxus',
    'Hero_Pestilence': 95,
    'Hero_Mumra':'Pharaoh',
    'Hero_WolfMan':'WarBeast',
    'Hero_Parasite': 194,
    'Hero_MonkeyKing': 197,
    'Hero_Empath': 168,
    'Hero_Martyr': 188,
    'Hero_Flux': 187,
    'Hero_Grinex': 228,
    'Hero_Prophet': 223,
    'Hero_Rally': 224,
    'Hero_Bushwack': 230,
    'Hero_Revenant': 196,
    'Hero_Aluna': 169,
    'Hero_Plant': 221,
    'Hero_Pearl': 227}

    #'Hero_Shaman': 43, 'Hero_Krixi': 20, 'Hero_Parasite': 194, 'Hero_MonkeyKing': 197, 'Hero_Treant': 25, 'Hero_Empath': 168, 'Hero_DiseasedRider': 108, 'Hero_Bubbles':125, 'Hero_Vanya': 26, 'Hero_Engineer': 122 
def hero(name):
    return heroes[name]
